// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var App = require("./components/App.js");
var Client = require("./apollo/Client.js");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ApolloProvider = require("reason-apollo/lib/js/src/ApolloProvider.bs.js");
var RegisterServiceWorker = require("./registerServiceWorker");

((require('./index.css')));

((require('tachyons/css/tachyons.css')));

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, ApolloProvider.make(Client.instance, /* array */[ReasonReact.element(/* None */0, /* None */0, App.make(/* array */[]))])), "root");

RegisterServiceWorker.default();

/*  Not a pure module */
