// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var ReRoute = require("reason-reroute/lib/js/src/ReRoute.js");

function routeFromUrl(url) {
  var match = url[/* path */0];
  if (match) {
    switch (match[0]) {
      case "RouteTestPage" : 
          if (match[1]) {
            return /* NotFound */4;
          } else {
            return /* RouteTestPage */3;
          }
      case "createpage" : 
          if (match[1]) {
            return /* NotFound */4;
          } else {
            return /* CreatePage */5;
          }
      case "detailpage" : 
          if (match[1]) {
            return /* NotFound */4;
          } else {
            return /* DetailPage */1;
          }
      case "draftspage" : 
          if (match[1]) {
            return /* NotFound */4;
          } else {
            return /* DraftsPage */2;
          }
      case "feedpage" : 
          if (match[1]) {
            return /* NotFound */4;
          } else {
            return /* FeedPage */0;
          }
      default:
        return /* NotFound */4;
    }
  } else {
    return /* FeedPage */0;
  }
}

function routeToUrl(route) {
  switch (route) {
    case 0 : 
        return "/feedpage";
    case 1 : 
        return "/detailpage";
    case 2 : 
        return "/draftspage";
    case 3 : 
        return "/RouteTestPage";
    case 4 : 
        return "/NotFound";
    case 5 : 
        return "/createpage";
    
  }
}

var Config = /* module */[
  /* routeFromUrl */routeFromUrl,
  /* routeToUrl */routeToUrl
];

var include = ReRoute.CreateRouter(Config);

var Container = include[0];

var Link = include[1];

exports.Config = Config;
exports.Container = Container;
exports.Link = Link;
/* include Not a pure module */
