// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Router = require("../Router.js");
var FeedPage = require("./FeedPage.js");
var NotFound = require("./NotFound.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var CreatePage = require("./CreatePage.js");
var DetailPage = require("./DetailPage.js");
var DraftsPage = require("./DraftsPage.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var RouteTestPage = require("./RouteTestPage.js");

var component = ReasonReact.statelessComponent("App");

function ste(prim) {
  return prim;
}

function makeCls(x) {
  return Belt_List.reduce(x, "", (function (a, b) {
                return a + (" " + b);
              }));
}

var nav = /* :: */[
  "pa3",
  /* :: */[
    "pa4-ns",
    /* [] */0
  ]
];

var feedRoute = /* :: */[
  "link",
  /* :: */[
    "dim",
    /* :: */[
      "black",
      /* :: */[
        "b",
        /* :: */[
          "f6",
          /* :: */[
            "f5-ns",
            /* :: */[
              "dib",
              /* :: */[
                "mr3",
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var draftsRoute = /* :: */[
  "link",
  /* :: */[
    "dim",
    /* :: */[
      "f6",
      /* :: */[
        "f5-ns",
        /* :: */[
          "dib",
          /* :: */[
            "mr3",
            /* :: */[
              "black",
              /* [] */0
            ]
          ]
        ]
      ]
    ]
  ]
];

var createRoute = /* :: */[
  "f6",
  /* :: */[
    "link",
    /* :: */[
      "dim",
      /* :: */[
        "br1",
        /* :: */[
          "ba",
          /* :: */[
            "ph3",
            /* :: */[
              "pv2",
              /* :: */[
                "fr",
                /* :: */[
                  "mb2",
                  /* :: */[
                    "dib",
                    /* :: */[
                      "black",
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var Styles = /* module */[
  /* nav */nav,
  /* feedRoute */feedRoute,
  /* draftsRoute */draftsRoute,
  /* createRoute */createRoute
];

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Curry._1(Router.Container[/* make */1], (function (currentRoute) {
                        var tmp;
                        switch (currentRoute) {
                          case 0 : 
                              tmp = ReasonReact.element(/* None */0, /* None */0, FeedPage.make(/* array */[]));
                              break;
                          case 1 : 
                              tmp = ReasonReact.element(/* None */0, /* None */0, DetailPage.make(/* None */0, /* array */[]));
                              break;
                          case 2 : 
                              tmp = ReasonReact.element(/* None */0, /* None */0, DraftsPage.make(/* array */[]));
                              break;
                          case 3 : 
                              tmp = ReasonReact.element(/* None */0, /* None */0, RouteTestPage.make(/* array */[]));
                              break;
                          case 4 : 
                              tmp = ReasonReact.element(/* None */0, /* None */0, NotFound.make(/* array */[]));
                              break;
                          case 5 : 
                              tmp = ReasonReact.element(/* None */0, /* None */0, CreatePage.make(/* None */0, /* array */[]));
                              break;
                          
                        }
                        return React.createElement("div", {
                                    className: makeCls(nav)
                                  }, React.createElement("ul", undefined, ReasonReact.element(/* None */0, /* None */0, Curry._2(Router.Link[/* make */1], /* FeedPage */0, /* array */[React.createElement("li", {
                                                      className: makeCls(feedRoute)
                                                    }, "Feed")])), ReasonReact.element(/* None */0, /* None */0, Curry._2(Router.Link[/* make */1], /* DraftsPage */2, /* array */[React.createElement("li", {
                                                      className: makeCls(draftsRoute)
                                                    }, "Drafts")])), ReasonReact.element(/* None */0, /* None */0, Curry._2(Router.Link[/* make */1], /* RouteTestPage */3, /* array */[React.createElement("li", {
                                                      className: makeCls(draftsRoute)
                                                    }, "RouteTestPage")])), ReasonReact.element(/* None */0, /* None */0, Curry._2(Router.Link[/* make */1], /* CreatePage */5, /* array */[React.createElement("li", {
                                                      className: makeCls(createRoute)
                                                    }, "+ Create Draft")]))), tmp);
                      })));
    });
  return newrecord;
}

exports.component = component;
exports.ste = ste;
exports.makeCls = makeCls;
exports.Styles = Styles;
exports.make = make;
/* component Not a pure module */
