// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Detail Page");

function make($staropt$star, _) {
  var title = $staropt$star ? $staropt$star[0] : "Detail Page";
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "App"
                }, React.createElement("div", {
                      className: "App-header"
                    }, React.createElement("h2", undefined, title)), React.createElement("p", {
                      className: "App-intro"
                    }, "To get started, edit", React.createElement("code", undefined, " src/app.re "), "and save to reload."));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
