// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var loading = /* :: */[
  "flex w-100 h-100 items-center justify-center pt7",
  /* [] */0
];

var Styles = /* module */[/* loading */loading];

function ste(prim) {
  return prim;
}

function makeCls(x) {
  return Belt_List.reduce(x, "", (function (a, b) {
                return a + (" " + b);
              }));
}

var component = ReasonReact.statelessComponent("RouteTestPage");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: makeCls(loading)
                }, React.createElement("div", undefined, "Testing ..."));
    });
  return newrecord;
}

exports.Styles = Styles;
exports.ste = ste;
exports.makeCls = makeCls;
exports.component = component;
exports.make = make;
/* component Not a pure module */
